<?php

/**
 * @file
 * Entity Registration waitlist functionality
 */

/**
 * Implements hook_registration_entity_settings().
 */
function registration_waitlist_registration_entity_settings($settings) {
  // add a settings element to enable adding registrations to the waitlist
  return array(
    'registration_waitlist_enable' => array(
      '#type' => 'checkbox',
      '#title' => t('Enable wait list'),
      '#description' => t('When wait list is enabled, registrations made after capacity has been reached will be set to the wait list state.'),
      '#default_value' => isset($settings['settings']['registration_waitlist_enable']) ? $settings['settings']['registration_waitlist_enable'] : array()
    )
  );
}

/**
 * Implements hook_default_ENTITY_TYPE().
 */
function registration_waitlist_default_registration_state() {
  $defaults = array();
  $defaults['registration_waitlist'] = entity_create('registration_state', array(
    'name' => 'registration_waitlist',
    'label' => 'Wait list',
    'description' => 'Special state for registrations after capacity is reached.',
    'default_state' => FALSE,
    'active' => FALSE,
    'show_on_form' => TRUE,
    'weight' => 0,
  ));
  return $defaults;
}