registration.registration_state.*:
  type: config_entity
  label: 'Registration state config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
