<?php

/**
 * @file
 * Entity Registration per entity access control
 */

/**
 * Implements hook_registration_entity_settings().
 */
function registration_entity_access_registration_entity_settings($settings) {
  // add a settings element for the user roles with registration access
  return array(
    'registration_entity_access_roles' => array(
      '#type' => 'checkboxes',
      '#title' => t('Roles that can register'),
      '#description' => t('Override the default access control settings by selecting which roles can %register for this event.', array('%register' => t('register'))),
      '#options' => user_roles(TRUE),
      '#default_value' => isset($settings['settings']['registration_entity_access_roles']) ? $settings['settings']['registration_entity_access_roles'] : array()
    )
  );
}

/**
 * Implements hook_registration_access().
 */
function registration_entity_access_registration_access($op, $registration = NULL, $account = NULL, $entity_type) {
  if ($op == 'create' && ($registration->entity_type && $registration->entity_id) && $account) {
    $settings = registration_entity_settings($registration->entity_type, $registration->entity_id);
    if (isset($settings['settings']['registration_entity_access_roles'])) {
      foreach ($settings['settings']['registration_entity_access_roles'] as $role_id) {
        if ($role_id && isset($account->roles[$role_id])) {
          return TRUE;
        }
      }
    }
  }
}
